name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> "${GITHUB_ENV}"
      - name: Package
        run: make package
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${TAG}" --repo="${GITHUB_REPOSITORY}" --title="Release ${TAG}" --generate-notes "build/jqp-${TAG}.tar.gz#jqp-${TAG}.tar.gz"
